version: '3.4'

services:
  mixmeal.web:
    image: ${DOCKER_REGISTRY-}mixmealweb
    build:
      context: .
      dockerfile: ../MixMeal.Web/Dockerfile

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw