// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MixMeal.Persistence.PostgreSQL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MixMeal.Persistence.PostgreSQL.Migrations
{
    [DbContext(typeof(MixMealDbContext))]
    [Migration("20220827073147_Setup")]
    partial class Setup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MixMeal.Core.Models.Dish", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("DishSize")
                        .HasColumnType("integer");

                    b.Property<int>("DishType")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("MixMeal.Core.Models.Ingredient", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<string>("DishName")
                        .HasColumnType("text");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision");

                    b.Property<bool>("Premium")
                        .HasColumnType("boolean");

                    b.Property<string>("ValidDishTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.HasIndex("DishName");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("MixMeal.Core.Models.Ingredient", b =>
                {
                    b.HasOne("MixMeal.Core.Models.Dish", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("DishName");
                });

            modelBuilder.Entity("MixMeal.Core.Models.Dish", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
