name: Test

on:
  push:
    branches:
      - '**'
      - '!main'

env:
    unit_test_project: "MixMeal.Web.UnitTests"
    latest_dotnet_version: "6.x"

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: '0'
      - name: Setup .NET Core SDK ${{ env.latest_dotnet_version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.latest_dotnet_version }}
      - name: Install dependencies
        run: dotnet restore $unit_test_project
      - name: Build
        run: dotnet build $unit_test_project --no-restore --configuration Release
      - name: Test
        run: dotnet test $unit_test_project --no-restore --logger:trx --results-directory "TestResults" 
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results
          path: "TestResults"
        if: ${{ always() }}